// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqtclciqdgfszprkzawo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdGNsY2lxZGdmc3pwcmt6YXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTcxNTIsImV4cCI6MjA2ODI3MzE1Mn0.TaZPp8DevVYuKKeGDsnImPltLM-SJYBRFS1IXZ2Npfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});